### ISSUE TITLE
Is Slack required?

### ISSUE THREAD

**Issue by TangJames** [azoff/tockstalk#3]
If I just wanted the bot running without the slack notifications, is that possible? If I get a reservation wouldn't I just get an email?

**Comment by azoff** [comment]
Totally! Short answer: just modify [the code](https://github.com/azoff/tockstalk/blob/main/cypress/support/commands.js) to avoid sending a call to slack.

Long answer: if you want this change, others will likely want it too. It would be great if you could contribute your changes back to the project. A complete change would look something like this:
1. Modify [this line](https://github.com/azoff/tockstalk/blob/main/cypress/support/commands.js#L2) to avoid creating a Webhook object if the webhook path does not exist in the cypress env. 
2. Modify the log function itself to avoid posting to the webhook, if the webhook itself is not defined (from the step above)
3. Modify the READMe to let future users know that they can avoid slack by just not defining the webhook URL in the cypress env. 
4. Submit a PR so that future users can benefit from your changes.

Thanks!

**Comment by TangJames** [comment]
I will work on this right now and submit a PR. Thanks!

**Comment by TangJames** [comment]
It looks like when you don't define the webhook the cypress fails because it isn't defined

**Comment by azoff** [comment]
I added support for this in [v1.1.0](https://github.com/azoff/tockstalk/releases/tag/v1.1.0). Just don't provide a webhook URL in the cypress env and it will avoid trying to connect to Slack. Let me know if that works for you!
